### PR TITLE
Update avconv to ffmpeg in convert.py, adjust filter parameters

### PR DESCRIPTION
**Pull request by BeeblebroxIV**

### CODE REVIEW

**Comment by Hvass-Labs** [comment]
I can see you are new to github so I will be polite. You need to explain why you want to make changes to a repo. You can't just open a PR and expect people to accept and merge it. In this case I believe ffmpeg is an obsolete version and avconv is the correct one to use.

**Comment by BeeblebroxIV** [comment]
Sorry for the inconvenience and thank you very much for understanding / staying polite. Even if this PR stays closed, I would like to explain a little: 

avconv (by the libav project) is a fork of the ffmpeg tool (by the FFmpeg project), but there hasn't been much active development recently on the former (see for example the top answer [here](https://superuser.com/questions/507386/why-would-i-choose-libav-over-ffmpeg-or-is-there-even-a-difference)).

Aside from the fact that there is not much active development, the libav-tools Ubuntu package is no longer included in newer distributions, with a message indicating that the ffmpeg package replaces it (which is how I came accross this topic in the first place).

I had assumed that the changes in this Pull Request might be useful seeing as people who want to use the script would like to try it (more or less) "out of the box" without having to manually download and install a two year old release from a dead project (which is still possible: https://libav.org/download/).

Sorry for the misunderstanding, and thanks again for giving me an answer.

**Comment by Hvass-Labs** [comment]
You should have started with this explanation :-)

Thanks for the suggestion. I think this script belongs to Tutorial 09 on Video Data, which only works with TensorFlow 1 and I no longer update those old tutorials. A few years ago ffmpeg was considered abandoned and they recommended using avconv. Now they've apparently flipped. In a few years they'll probably flip back again. I would also have to check that your modification is correct and works. It's not really worth the hassle for me, so I'm just going to leave it as it is. If somebody else has the same problem, they'll hopefully come across your solution here. Thanks!

**Comment by BeeblebroxIV** [comment]
Makes sense to me! Thanks for your time.

**Pull request closed without merging**
