### PR TITLE
add Docker support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Hvass-Labs** [comment]
Thanks for the suggestion.

I have never used Docker myself, so I would like someone else to test if they can get this working on their machines as well.

@johndpope would you mind trying this? You talked about Docker in pull request https://github.com/Hvass-Labs/TensorFlow-Tutorials/pull/27

@sorend have you used Docker? Could you try if this works for you as well?

**Comment by ghost** [comment]
Thanks.

To test, please follow these steps: (See  [Makefile](https://github.com/ontouchstart/TensorFlow-Tutorials/blob/75227cbe76ce54c4295f20b65cc54a7e814eb22c/Makefile) for details.)

- Install docker on your [Mac](https://docs.docker.com/docker-for-mac/)/[Windows](https://docs.docker.com/docker-for-windows).
- `make docker` to build a local docker image on your computer.
- `make notebooks` to launch Juypter notebook.
- `make tensorboard` to launch tensorboard.

**Comment by Hvass-Labs** [comment]
Thanks again for the pull request. It seems I will have to test it myself. I need to understand and test it better before I merge into master. As I have a lot of work at the moment and I haven't used Docker before, it'll be a while before I can get around to it. But I'll leave the issue open and you can update the files if you need to. Other people can download them as well if they need Docker support for these tutorials.

**Comment by ghost** [comment]
@Hvass-Labs Since you added [requirements.txt](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/requirements.txt) in the last update, your tutorials now work with [binder](http://mybinder.org), you can run binder docker vm at this URL: http://mybinder.org/repo/hvass-labs/tensorflow-tutorials. If you have new code, just rebuild at this URL: http://mybinder.org/status/hvass-labs/tensorflow-tutorials

Here are a few screenshots of running binder vm on iPhone:

img_3808

img_3809

img_3810

Since the Docker solution is found, I will close this PR. For people who need a `Dockerfile`, they might want to use [the binder version](http://docs.mybinder.org/example-dockerfile):

```
FROM andrewosh/binder-base:latest

RUN mkdir /home/main/notebooks
RUN chown main:main /home/main/notebooks
WORKDIR /home/main/notebooks
USER root
COPY . /home/main/notebooks/
RUN chown -R main:main $HOME/notebooks
USER main

RUN find $HOME/notebooks -name '*.ipynb' -exec jupyter trust {} \;


ADD requirements.txt requirements.txt
ADD handle-requirements.py handle-requirements.py
RUN python handle-requirements.py

USER main
WORKDIR $HOME/notebooks
```

Thanks for the good work.

**Pull request closed without merging**
