### PR TITLE
requirements

### PR DESCRIPTION
**Pull request by johndpope**

### CODE REVIEW

**Comment by Hvass-Labs** [comment]
Thanks for the suggestion!

It is a good idea, but different tutorials require different packages. For example, I'm working on something now that requires packages that none of the other tutorials require. So it's not necessary to install those packages if you only want to run a few of the other tutorials.

Perhaps I should make a list in the README.md with the packages instead of a requirements.txt file.

What do you think? Can you explain a bit more why you think requirements.txt would be good to have?

**Comment by johndpope** [comment]
I guess if you wanted to avoid having a giant bloated requirements file - 
then having a commented out line per notebook could be second option. 
I have used anaconda before - and re-reading the readme this is your recommended approach -  I use brew /pip and have stayed away from anaconda as I once had a bad experience with it 
// 
// pip3 install pillow tensorflow etc

pip install plays well with dockerfiles (where you can quickly boot up a self contained machine)
eg.
https://gist.github.com/search?utf8=%E2%9C%93&q=dockerfile+pip


https://github.com/search?utf8=%E2%9C%93&q=docker+ml&type=

eg.
https://github.com/nitnelave/docker-ml

in a few lines of code you can have a docker container up and running.

**Comment by johndpope** [comment]
I really enjoyed your tutorial.  
If you ever do any more videos - would love to see some maths thrown in - here's a peak from another video giving a high overview of maths https://youtu.be/V0glxY6fHTY?t=5625

I've got my eye on this white paper - but maths is a bit daunting / although re-visting the above video feeling more confident. 
https://arxiv.org/pdf/1703.07511.pdf

**Comment by Hvass-Labs** [comment]
How about `tensorflow` vs. `tensorflow-gpu`? How would that work with `requirements.txt`? Would you suggest adding that as a commented line as well?

----

Thanks for the compliment on the tutorials! I thought about doing more maths but I decided to focus on implementation aspects. Honestly, I don't find the math aspects very interesting. I'm more interested in what you can build with higher-level building blocks. In fact, I'm not even a very big fan of neural networks. The stuff I'm currently working on really shows how antiquated they are. Unfortunately they are the best we currently have. I find that you can easily become bogged down in low-level details and loose sight of what you wanted to accomplish.

Fascinating paper you linked. Those are really good results. I just took a quick look but I don't have time to do more tutorials on this topic. You should write the authors and ask them to do a youtube tutorial on it. It really is a pity that old-fashioned papers are still the preferred means of communication in such a high-tech field. Python Notebooks and YouTube is really the way to go if you want to reach a wide audience.

**Comment by Hvass-Labs** [comment]
Thanks again for the suggestion, it was actually a great idea that has made the installation procedure much easier. I just needed to understand how it worked.

I've added a `requirements.txt` to the repository, please have a look if this does what you want. I have also updated the README to reflect this change.

A few comments:

I investigated more about the possibilities of `requirements.txt` and it appears that you can pass different options to it, so we could install either CPU or GPU versions of TensorFlow using something like this in `requirements.txt`, if I understand correctly:

    tensorflow --install-option='cpu'
    tensorflow-gpu --install-option='gpu'

However, this apparently causes pip to not use wheels anymore so the packages would have to be built on every installation, if I understand correctly. This would clearly be undesirable.

I also thought about having multiple files e.g. `requirements-base.txt` and `requirements-cpu.txt` and `requirements-gpu.txt` that would use the base, but it will quickly become a mess with more options than just CPU/GPU.

The simple solution that I chose, was to just put some comments in the file and people will then have to edit the file before running `pip install -r requirements.txt`.

**Pull request closed without merging**
